/**
 * The KYVON character model: states, pets, and the preset a visitor saves.
 *
 * This file is deliberately free of any 3D or AI dependency. The states are
 * what the viewer animates and what the AI pipeline drives, so keeping them as
 * plain data means both sides can be tested without a WebGL context or a
 * provider key — and the preset can be validated before anything renders.
 */

/**
 * What KYVON is doing, which drives animation, expression and status text.
 *
 * `offline` and `error` exist as first-class states rather than being folded
 * into `idle`: a companion that looks calm while its backend is unreachable is
 * telling the user something false, and this project's recurring defect has
 * been exactly that.
 */
export type CharacterState =
  | 'idle'
  | 'listening'
  | 'thinking'
  | 'speaking'
  | 'happy'
  | 'concerned'
  | 'warning'
  | 'success'
  | 'offline'
  | 'error';

export interface StatePresentation {
  /** Animation clip name as exported from Blender. */
  clip: string;
  label: string;
  /** Token name, not a raw colour — status must not depend on colour alone. */
  tone: 'neutral' | 'active' | 'positive' | 'caution' | 'danger' | 'muted';
  /** Read by assistive technology; every state is announced, not just shown. */
  announce: string;
}

export const STATES: Record<CharacterState, StatePresentation> = {
  idle: { clip: 'Idle', label: 'Idle', tone: 'neutral', announce: 'KYVON is idle' },
  listening: { clip: 'Idle', label: 'Listening', tone: 'active', announce: 'KYVON is listening' },
  thinking: { clip: 'Idle', label: 'Thinking', tone: 'active', announce: 'KYVON is thinking' },
  speaking: { clip: 'Idle', label: 'Speaking', tone: 'active', announce: 'KYVON is speaking' },
  happy: { clip: 'Idle', label: 'Happy', tone: 'positive', announce: 'KYVON is happy' },
  concerned: { clip: 'Idle', label: 'Concerned', tone: 'caution', announce: 'KYVON is concerned' },
  warning: { clip: 'Idle', label: 'Warning', tone: 'caution', announce: 'KYVON has a warning' },
  success: { clip: 'Idle', label: 'Success', tone: 'positive', announce: 'Operation succeeded' },
  offline: { clip: 'Idle', label: 'Offline', tone: 'muted', announce: 'KYVON is offline' },
  error: { clip: 'Idle', label: 'Error', tone: 'danger', announce: 'KYVON encountered an error' },
};

/**
 * Only `Idle` is a real clip today — it is the one the Blender pipeline bakes.
 * The others map onto it so the UI can already express state through the label
 * and tone while the animation set is still one clip, rather than referencing
 * clips that do not exist and silently rendering a T-pose.
 */
export const AVAILABLE_CLIPS = ['Idle'] as const;

export interface Pet {
  id: string;
  name: string;
  species: string;
  /** Path under `public/`, generated by assets/blender/scripts/generate_pets.py */
  model: string;
  personality: string[];
  description: string;
}

export const PETS: Pet[] = [
  {
    id: 'k10',
    name: 'K-10',
    species: 'Cat',
    model: '/models/k10.glb',
    personality: ['Loyal', 'Smart', 'Curious'],
    description: 'The default companion. Calm while your infrastructure is calm.',
  },
  {
    id: 'k11',
    name: 'K-11',
    species: 'Fox',
    model: '/models/k11.glb',
    personality: ['Quick', 'Alert', 'Independent'],
    description: 'Reacts fastest to change; suits noisy environments.',
  },
  {
    id: 'k12',
    name: 'K-12',
    species: 'Dog',
    model: '/models/k12.glb',
    personality: ['Steady', 'Protective', 'Warm'],
    description: 'Least distracting. A good choice for long operational sessions.',
  },
  {
    id: 'k13',
    name: 'K-13',
    species: 'Owl',
    model: '/models/k13.glb',
    personality: ['Watchful', 'Precise', 'Quiet'],
    description: 'Built for observation. Moves only when something changes.',
  },
  {
    id: 'k14',
    name: 'K-14',
    species: 'Drone',
    model: '/models/k14.glb',
    personality: ['Exact', 'Tireless', 'Neutral'],
    description: 'No animal metaphor. For operators who want an instrument, not a pet.',
  },
];

export type Variant = 'kyvon-m' | 'kyvon-f';

export interface Character {
  id: Variant;
  name: string;
  role: string;
  personality: string[];
  /** Null until a rigged character asset exists — see docs/kyvon-assets.md. */
  model: string | null;
}

export const CHARACTERS: Character[] = [
  {
    id: 'kyvon-m',
    name: 'KYVON-M',
    role: 'AI DevOps companion',
    personality: ['Concise', 'Technical', 'Calm'],
    model: null,
  },
  {
    id: 'kyvon-f',
    name: 'KYVON-F',
    role: 'AI DevOps companion',
    personality: ['Concise', 'Technical', 'Calm'],
    model: null,
  },
];

/**
 * A saved character configuration.
 *
 * Appearance only. No field here may reference a server, a credential or any
 * infrastructure identifier: a preset is meant to be exportable and shareable,
 * so anything secret placed in it would leak the moment someone shared their
 * KYVON. `isSafePreset` enforces that rather than leaving it to review.
 */
export interface CharacterPreset {
  version: 1;
  characterId: Variant;
  petId: string;
  expression: CharacterState;
  accentColor: string;
}

export const DEFAULT_PRESET: CharacterPreset = {
  version: 1,
  characterId: 'kyvon-m',
  petId: 'k10',
  expression: 'idle',
  accentColor: '#38bdf8',
};

/** Keys that must never appear in a preset, at any depth. */
const FORBIDDEN = [
  'key',
  'token',
  'secret',
  'password',
  'passphrase',
  'credential',
  'ssh',
  'host',
  'server',
  'api',
  'auth',
  'cookie',
];

/**
 * Reject a preset carrying anything that looks like a credential or an
 * infrastructure identifier.
 *
 * Applied on load as well as on save, because a preset can arrive from a file
 * or a shared link — untrusted input, not just our own output.
 */
export function isSafePreset(value: unknown): value is CharacterPreset {
  if (typeof value !== 'object' || value === null) return false;
  const preset = value as Record<string, unknown>;

  if (preset.version !== 1) return false;
  if (!CHARACTERS.some((c) => c.id === preset.characterId)) return false;
  if (!PETS.some((p) => p.id === preset.petId)) return false;
  if (typeof preset.expression !== 'string' || !(preset.expression in STATES)) return false;
  if (typeof preset.accentColor !== 'string' || !/^#[0-9a-f]{6}$/i.test(preset.accentColor)) {
    return false;
  }

  // An unexpected key is refused rather than ignored: silently dropping it
  // would let a crafted preset round-trip through a share link.
  const allowed = new Set(Object.keys(DEFAULT_PRESET));
  for (const key of Object.keys(preset)) {
    if (!allowed.has(key)) return false;
    if (FORBIDDEN.some((f) => key.toLowerCase().includes(f))) return false;
  }
  return true;
}
